dependencies:
- name: bdd-test-create-spring-1532956844
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-golang-http-1532956844
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-import-1532956844
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.0
- name: bdd-test-node-http-1532956844
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-test-python-http-1532956844
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
